[package]
name = "teamspace-one"
version = "0.1.0"
description = "Teamspace One native desktop client"
authors = ["Teamspace"]
edition = "2021"
exclude = ["gen/", "target/"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-notification = "2"
tauri-plugin-deep-link = "2"
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
keyring = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-http = { version = "2.6.0", features = ["unsafe-headers"] }
base64 = "0.22"
image = "0.25"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
tracing = "0.1"

[target.'cfg(any(windows, target_os = "macos", target_os = "linux"))'.dependencies]
nokhwa = { version = "0.10.10", features = ["input-native", "decoding"] }
cpal = "0.15.3"
webrtc = "0.17.1"
scap = "0.0.8"
tokio-tungstenite = "0.21"
futures = "0.3"
tauri-plugin-global-shortcut = "2"
tauri-plugin-process = "2"
tauri-plugin-updater = "2"
tauri-plugin-single-instance = "2"

[target.'cfg(windows)'.dependencies]
windows-capture = "=1.4.2"

[dev-dependencies]
tauri = { version = "2", features = ["devtools"] }
