export const Subjects = {
  USER_CREATED: 'teamspace-one.user.created',
  USER_UPDATED: 'teamspace-one.user.updated',
  USER_SIGNED_IN: 'teamspace-one.user.signed_in',
  ORGANISATION_CREATED: 'teamspace-one.organisation.created',
  ORGANISATION_MEMBER_ADDED: 'teamspace-one.organisation.member_added',
  WORKSPACE_CREATED: 'teamspace-one.workspace.created',
  PROJECT_CREATED: 'teamspace-one.project.created',
  PROJECT_UPDATED: 'teamspace-one.project.updated',
  PROJECT_DELETED: 'teamspace-one.project.deleted',
  PROJECT_COMMENT_CREATED: 'teamspace-one.project.comment.created',
  PROJECT_COMMENT_UPDATED: 'teamspace-one.project.comment.updated',
  PROJECT_COMMENT_DELETED: 'teamspace-one.project.comment.deleted',
  PROJECT_ATTACHMENT_ADDED: 'teamspace-one.project.attachment.added',
  PROJECT_ATTACHMENT_REMOVED: 'teamspace-one.project.attachment.removed',
  CHANNEL_CREATED: 'teamspace-one.channel.created',
  CHANNEL_UPDATED: 'teamspace-one.channel.updated',
  CHANNEL_DELETED: 'teamspace-one.channel.deleted',
  CHANNEL_MEMBERS_UPDATED: 'teamspace-one.channel.members_updated',
  MESSAGE_CREATED: 'teamspace-one.message.created',
  MESSAGE_UPDATED: 'teamspace-one.message.updated',
  MESSAGE_DELETED: 'teamspace-one.message.deleted',
  TASK_CREATED: 'teamspace-one.task.created',
  TASK_UPDATED: 'teamspace-one.task.updated',
  TASK_COMPLETED: 'teamspace-one.task.completed',
  FILE_UPLOADED: 'teamspace-one.file.uploaded',
  FILE_PROCESSED: 'teamspace-one.file.processed',
  FILE_DELETED: 'teamspace-one.file.deleted',
  MEETING_CREATED: 'teamspace-one.meeting.created',
  MEETING_STARTED: 'teamspace-one.meeting.started',
  MEETING_ENDED: 'teamspace-one.meeting.ended',
  MEETING_PARTICIPANT_JOINED: 'teamspace-one.meeting.participant.joined',
  MEETING_PARTICIPANT_LEFT: 'teamspace-one.meeting.participant.left',
  MEETING_SCREEN_SHARED: 'teamspace-one.meeting.screen.shared',
  VOICE_ROOM_CREATED: 'teamspace-one.voice.room.created',
  AI_SUMMARY_COMPLETED: 'teamspace-one.ai.summary_completed',
  AI_DOCUMENT_INDEXED: 'teamspace-one.ai.document_indexed',
  AI_QUESTION_ANSWERED: 'teamspace-one.ai.question_answered',
  AI_TASK_EXTRACTED: 'teamspace-one.ai.task_extracted',
  AI_DECISION_EXTRACTED: 'teamspace-one.ai.decision_extracted',
  AI_ACTION_CONFIRMED: 'teamspace-one.ai.action_confirmed',
  NOTIFICATION_CREATED: 'teamspace-one.notification.created',

  // Phase 9 - client collaboration
  GUEST_CREATED: 'teamspace-one.guest.created',
  GUEST_INVITED: 'teamspace-one.guest.invited',
  CLIENT_CREATED: 'teamspace-one.client.created',
  CLIENT_UPDATED: 'teamspace-one.client.updated',
  CLIENT_DELETED: 'teamspace-one.client.deleted',
  CLIENT_PROJECT_CREATED: 'teamspace-one.client_project.created',
  APPROVAL_CREATED: 'teamspace-one.approval.created',
  APPROVAL_APPROVED: 'teamspace-one.approval.approved',
  APPROVAL_REJECTED: 'teamspace-one.approval.rejected',
  FILE_SHARED_EXTERNALLY: 'teamspace-one.file.shared_externally',
} as const;

export type Subject = (typeof Subjects)[keyof typeof Subjects];
