export const Subjects = {
  USER_CREATED: 'teamspace-one.user.created',
  USER_UPDATED: 'teamspace-one.user.updated',
  USER_SIGNED_IN: 'teamspace-one.user.signed_in',
  PASSWORD_RESET_REQUESTED: 'teamspace-one.user.password_reset_requested',
  ORGANISATION_CREATED: 'teamspace-one.organisation.created',
  ORGANISATION_MEMBER_ADDED: 'teamspace-one.organisation.member_added',
  MEMBER_INVITED: 'teamspace-one.organisation.member_invited',
  HRMS_EMPLOYEE_CREATE: 'teamspace-one.hrms.employee.created',
  HRMS_LEAVE_REQUESTED: 'teamspace-one.hrms.leave.requested',
  HRMS_LEAVE_APPROVED: 'teamspace-one.hrms.leave.approved',
  HRMS_LEAVE_REJECTED: 'teamspace-one.hrms.leave.rejected',
  HRMS_ATTENDANCE_CORRECTION_REQUESTED: 'teamspace-one.hrms.attendance.correction.requested',
  HRMS_ATTENDANCE_CORRECTION_RESOLVED: 'teamspace-one.hrms.attendance.correction.resolved',
  WORKSPACE_CREATED: 'teamspace-one.workspace.created',
  PROJECT_CREATED: 'teamspace-one.project.created',
  PROJECT_UPDATED: 'teamspace-one.project.updated',
  PROJECT_DELETED: 'teamspace-one.project.deleted',
  PROJECT_COMMENT_CREATED: 'teamspace-one.project.comment.created',
  PROJECT_COMMENT_UPDATED: 'teamspace-one.project.comment.updated',
  PROJECT_COMMENT_DELETED: 'teamspace-one.project.comment.deleted',
  PROJECT_ATTACHMENT_ADDED: 'teamspace-one.project.attachment.added',
  PROJECT_ATTACHMENT_REMOVED: 'teamspace-one.project.attachment.removed',
  CHANNEL_CREATED: 'teamspace-one.channel.created',
  CHANNEL_UPDATED: 'teamspace-one.channel.updated',
  CHANNEL_DELETED: 'teamspace-one.channel.deleted',
  CHANNEL_MEMBERS_UPDATED: 'teamspace-one.channel.members_updated',
  MESSAGE_CREATED: 'teamspace-one.message.created',
  MESSAGE_UPDATED: 'teamspace-one.message.updated',
  MESSAGE_DELETED: 'teamspace-one.message.deleted',
  MESSAGE_REACTION_UPDATED: 'teamspace-one.message.reaction.updated',
  TASK_CREATED: 'teamspace-one.task.created',
  TASK_UPDATED: 'teamspace-one.task.updated',
  TASK_COMPLETED: 'teamspace-one.task.completed',
  TASK_ATTACHMENT_ADDED: 'teamspace-one.task.attachment.added',
  TASK_ATTACHMENT_REMOVED: 'teamspace-one.task.attachment.removed',
  FILE_UPLOADED: 'teamspace-one.file.uploaded',
  FILE_PROCESSED: 'teamspace-one.file.processed',
  FILE_DELETED: 'teamspace-one.file.deleted',
  MEETING_CREATED: 'teamspace-one.meeting.created',
  MEETING_REMINDER: 'teamspace-one.meeting.reminder',
  MEETING_STARTED: 'teamspace-one.meeting.started',
  MEETING_ENDED: 'teamspace-one.meeting.ended',
  MEETING_RECORDING_TRANSCRIPT_READY: 'teamspace-one.meeting.recording.transcript.ready',
  MEETING_PARTICIPANT_JOINED: 'teamspace-one.meeting.participant.joined',
  MEETING_PARTICIPANT_LEFT: 'teamspace-one.meeting.participant.left',
  MEETING_SCREEN_SHARED: 'teamspace-one.meeting.screen.shared',
  MEETING_CHAT_CREATED: 'teamspace-one.meeting.chat.created',
  MEETING_REACTION_CREATED: 'teamspace-one.meeting.reaction.created',
  MEETING_RAISE_HAND_CHANGED: 'teamspace-one.meeting.raise_hand.changed',
  MEETING_RECORDING_STARTED: 'teamspace-one.meeting.recording.started',
  MEETING_RECORDING_STOPPED: 'teamspace-one.meeting.recording.stopped',
  VOICE_ROOM_CREATED: 'teamspace-one.voice.room.created',
  AI_SUMMARY_COMPLETED: 'teamspace-one.ai.summary_completed',
  AI_SUMMARY_CONFIRMED: 'teamspace-one.ai.summary_confirmed',
  AI_DOCUMENT_INDEXED: 'teamspace-one.ai.document_indexed',
  AI_QUESTION_ANSWERED: 'teamspace-one.ai.question_answered',
  AI_TASK_EXTRACTED: 'teamspace-one.ai.task_extracted',
  AI_DECISION_EXTRACTED: 'teamspace-one.ai.decision_extracted',
  AI_ACTION_REQUESTED: 'teamspace-one.ai.action_requested',
  AI_ACTION_CONFIRMED: 'teamspace-one.ai.action_confirmed',
  INTERVIEW_SESSION_SCHEDULED: 'teamspace-one.interview.session.scheduled',
  INTERVIEW_SESSION_REMINDER: 'teamspace-one.interview.session.reminder',
  INTERVIEW_SCREENING_COMPLETED: 'teamspace-one.interview.screening.completed',
  INTERVIEW_EVALUATION_READY: 'teamspace-one.interview.evaluation.ready',
  NOTIFICATION_CREATED: 'teamspace-one.notification.created',

  // Phase 9 - client collaboration
  GUEST_CREATED: 'teamspace-one.guest.created',
  GUEST_INVITED: 'teamspace-one.guest.invited',
  CLIENT_CREATED: 'teamspace-one.client.created',
  CLIENT_UPDATED: 'teamspace-one.client.updated',
  CLIENT_DELETED: 'teamspace-one.client.deleted',
  CLIENT_PROJECT_CREATED: 'teamspace-one.client_project.created',
  APPROVAL_CREATED: 'teamspace-one.approval.created',
  APPROVAL_APPROVED: 'teamspace-one.approval.approved',
  APPROVAL_REJECTED: 'teamspace-one.approval.rejected',
  FILE_SHARED_EXTERNALLY: 'teamspace-one.file.shared_externally',

  // Internal support tickets
  TICKET_CREATED: 'teamspace-one.ticket.created',
  TICKET_STATUS_CHANGED: 'teamspace-one.ticket.status_changed',
} as const;

export type Subject = (typeof Subjects)[keyof typeof Subjects];
